const ItemDetails = {
  Pies: [
    {
      id: '10',
      name: 'Shepherd\'s Pie',
      desc: 'Ground meat pie with a crust or topping of mashed potato',
      price: 35,
      unit: '',
      image: '/images/shepherds.jpg',
    },
    {
      id: '11',
      name: 'Savoury Mince',
      desc: 'Puffpastry filled with ground meat, onions, carrots in a meaty sauce',
      price: 30,
      unit: '',
      image: '/images/savoury.jpg',
    },
    {
      id: '12',
      name: 'Chicken Mushroom',
      desc: 'Puffpastry with the filling made up of chicken and mushrooms in a creamy sauce',
      price: 35,
      unit: '',
      image: '/images/chi_mush.jpg',
    },
    {
      id: '13',
      name: 'Veg',
      desc: 'Puffpastry filled with a combination of vegetables in a creamy sauce',
      price: 25,
      unit: '',
      image: '',
    },
    {
      id: '14',
      name: 'Cheese',
      desc: 'Savoury pastry filled with a mixture of cheese and onions',
      price: 30,
      unit: '',
      image: '',
    },
  ],
  Puffs: [
    {
      id: '1',
      name: 'Chicken',
      desc: '',
      price: 25,
      unit: 'piece',
      image: '/images/chi_puff.jpg',
    },
    {
      id: '2',
      name: 'Veg',
      desc: '',
      price: 18,
      unit: 'piece',
      image: '',
    },
    {
      id: '3',
      name: 'Cheese',
      desc: '',
      price: 20,
      unit: 'piece',
      image: '',
    },
    {
      id: '4',
      name: 'Egg',
      desc: '',
      price: 20,
      unit: 'piece',
      image: '',
    },
    {
      id: '5',
      name: 'Egg and Cheese',
      desc: '',
      price: 25,
      unit: 'piece',
      image: '',
    },
  ],
  Bread: [
    {
      id: '6',
      name: 'Chicken Buns',
      desc: '',
      price: 45,
      unit: 'piece',
      image: '/images/chi_bun.jpg',
    },
    {
      id: '7',
      name: 'Veg Buns',
      desc: '',
      price: 35,
      unit: 'piece',
      image: '',
    },
    {
      id: '8',
      name: 'Sausage Buns',
      desc: '',
      price: 45,
      unit: 'piece',
      image: '',
    },
    {
      id: '9',
      name: 'Chiroz Buns',
      desc: '',
      price: 45,
      unit: 'piece',
      image: '',
    },
  ],
  'Baked Mains': [
    {
      id: '15',
      name: 'Pasta Bechamel (W) - Veg',
      desc: '',
      price: 150,
      unit: '',
      image: '',
    },
    {
      id: '16',
      name: 'Pasta Bechamel (W) - Non Veg',
      desc: '',
      price: 200,
      unit: '',
      image: '',
    },
    {
      id: '17',
      name: 'Pasta Arrabiata (R) - Veg',
      desc: '',
      price: 150,
      unit: '',
      image: '',
    },
    {
      id: '18',
      name: 'Pasta Arrabiata (R) - Non Veg',
      desc: '',
      price: 200,
      unit: '',
      image: '',
    },
    {
      id: '19',
      name: 'Spaghetti Bolognese - Veg',
      desc: '',
      price: 200,
      unit: '',
      image: '/images/spaghetti_bolognese.jpg',
    },
    {
      id: '20',
      name: 'Spaghetti Bolognese - Non Veg',
      desc: '',
      price: 250,
      unit: '',
      image: '',
    },
    {
      id: '21',
      name: 'Lasagna - Veg',
      desc: '',
      price: 175,
      unit: '',
      image: '',
    },
    {
      id: '22',
      name: 'Lasagna - Non Veg',
      desc: '',
      price: 225,
      unit: '',
      image: '',
    },
    {
      id: '23',
      name: 'Quiche - Veg',
      desc: '',
      price: 175,
      unit: '',
      image: '',
    },
    {
      id: '24',
      name: 'Quiche - Non Veg',
      desc: '',
      price: 225,
      unit: '',
      image: '',
    },
    {
      id: '25',
      name: 'Baked Chicken, White Sauce',
      desc: '',
      price: 200,
      unit: '',
      image: '',
    },
    {
      id: '26',
      name: 'Chicken and Mushroom',
      desc: '',
      price: 200,
      unit: '',
      image: '',
    },
    {
      id: '27',
      name: 'Vegetable',
      desc: '',
      price: 150,
      unit: '',
      image: '',
    },
    {
      id: '28',
      name: 'Cheesy Garlic Pasta',
      desc: '',
      price: 175,
      unit: '',
      image: '',
    },
    {
      id: '29',
      name: 'Spinach and Corn',
      desc: '',
      price: 150,
      unit: '',
      image: '',
    },
    {
      id: '30',
      name: 'Mac and Cheese',
      desc: '',
      price: 175,
      unit: '',
      image: '/images/mac_cheese.jpg',
    },
    {
      id: '31',
      name: 'Baked Roasted Chicken',
      desc: 'Spicy / Pepper',
      price: 700,
      unit: 'kg',
      image: '',
    },
  ],
  Brownies: [
    {
      id: '32',
      name: 'Plain',
      desc: '',
      price: 40,
      unit: 'piece',
      image: '/images/brownies.jpg',
    },
    {
      id: '33',
      name: 'Peanut Butter',
      desc: '',
      price: 45,
      unit: 'piece',
      image: '',
    },
    {
      id: '34',
      name: 'Chocolate Ganache',
      desc: '',
      price: 45,
      unit: 'piece',
      image: '',
    },
    {
      id: '35',
      name: 'Walnut',
      desc: '',
      price: 50,
      unit: 'piece',
      image: '',
    },
    {
      id: '36',
      name: 'Choco Chip',
      desc: '',
      price: 45,
      unit: 'piece',
      image: '',
    },
    {
      id: '37',
      name: 'Salted Caramel',
      desc: '',
      price: 45,
      unit: 'piece',
      image: '',
    },
  ],
  Cupcakes: [
    {
      id: '38',
      name: '',
      desc: '',
      price: 40,
      unit: 'piece',
      image: '',
    },
  ],
  Cookies: [
    {
      id: '39',
      name: 'Butter',
      desc: '',
      price: 15,
      unit: 'piece',
      image: '',
    },
    {
      id: '40',
      name: 'Choco Chip',
      desc: '',
      price: 15,
      unit: 'piece',
      image: '',
    },
    {
      id: '41',
      name: 'Peanut Butter',
      desc: '',
      price: 15,
      unit: 'piece',
      image: '',
    },
    {
      id: '42',
      name: 'Chocolate',
      desc: '',
      price: 15,
      unit: 'piece',
      image: '',
    },
    {
      id: '43',
      name: 'Double Chocolate',
      desc: '',
      price: 15,
      unit: 'piece',
      image: '',
    },
    {
      id: '44',
      name: 'Salted',
      desc: '',
      price: 15,
      unit: 'piece',
      image: '',
    },
    {
      id: '45',
      name: 'Nankaties',
      desc: '',
      price: 15,
      unit: 'piece',
      image: '',
    },
  ],
  Desserts: [
    {
      id: '46',
      name: 'Mouse',
      desc: 'Mango / Strawberry / Pineapple / Nutella / Chocolate',
      price: 200,
      unit: '',
      image: '',
    },
    {
      id: '47',
      name: 'Trifle Pudding',
      desc: '',
      price: 200,
      unit: '',
      image: '',
    },
    {
      id: '48',
      name: 'Guava Cheese Chocolate Fudge',
      desc: '',
      price: 250,
      unit: '',
      image: '',
    },
    {
      id: '49',
      name: 'Chocolate Rum Balls',
      desc: '',
      price: 200,
      unit: '',
      image: '',
    },
    {
      id: '50',
      name: 'Marzipan',
      desc: '',
      price: 200,
      unit: '',
      image: '',
    },
  ],
  Cakes: [
    {
      id: '51',
      name: 'Tea Cakes',
      desc: 'Vanilla / Chocolate / Coffee / Marble / Carrot / Lemon / Orange / Banana',
      price: 600,
      unit: 'kg',
      image: '',
    },
    {
      id: '52',
      name: 'Butter Cream Cake',
      desc: '',
      price: 700,
      unit: 'kg',
      image: '',
    },
    {
      id: '53',
      name: 'Whipped Cream Cake',
      desc: '',
      price: 700,
      unit: 'kg',
      image: '',
    },
    {
      id: '54',
      name: 'Ganache',
      desc: '',
      price: 700,
      unit: 'kg',
      image: '',
    },
    {
      id: '55',
      name: 'Fondant',
      desc: '',
      price: 800,
      unit: 'kg',
      image: '',
    },
    {
      id: '56',
      name: 'Customized Cakes',
      desc: 'Based on design',
      price: 0,
      unit: '',
      image: '',
    },
  ],
}
module.exports = ItemDetails
